[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "HOST=0.0.0.0 PORT=9000 npx medusa db:migrate && cd .medusa/server && HOST=0.0.0.0 PORT=9000 node index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
internalPort = 9000
