services:
  - type: web
    name: sicaru-backend
    runtime: node
    plan: starter
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISABLE_ADMIN
        value: "false"
